version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: productdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  product-service:
    build: 
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_URLS=http://*:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=productdb;Username=postgres;Password=password
    depends_on:
      - postgres

volumes:
  postgres_data:
