global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'product-service'
    static_configs:
      - targets: ['host.docker.internal:5000']  # Access host from Docker
    metrics_path: /metrics
    scrape_interval: 10s
